### ISSUE TITLE
error at the start

### ISSUE THREAD

**Issue by oivil** [dougmassay/kindleimport-sigil-plugin#1]
Stato: failed
Launcher: missing or incorrect paths passed in

**Comment by dougmassay** [comment]
Not nearly enough info provided for me to help with this.

Platform?
If Linux, what flavor? And did you install from repositories or build Sigil yourself?
Sigil version?
Plugin version?

Most plugin configuration issues are better solved using the Sigil user forums at MobileRead. The issue database is for reporting bugs and feature requests. The link for the plugin support thread at mobileread is in the README.

**Comment by dougmassay** [comment]
Feel free to reopen this if or when you have more details to report.
